import type { Metadata } from "next";
import { ArrowUpRight, MapPin } from "lucide-react";
import Link from "next/link";


export const metadata: Metadata = { title: "About", description: "About NasLabs and its founder, Rifki Anashirul.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <main className="inner-page section-shell"><div className="inner-hero"><p className="eyebrow"><span className="eyebrow-dot" /> About NasLabs</p><h1>A small studio<br /><em>with room to think.</em></h1><p>NasLabs is an independent software development studio founded and led by Rifki Anashirul (Kinas).</p></div><section className="founder-profile"><div className="profile-visual" aria-label="Profile visual for Rifki Anashirul"><span>RA</span><small>RIFKI<br />ANASHIRUL</small><i /></div><div className="founder-bio"><p className="eyebrow">The person behind NasLabs</p><h2>Hi, I&apos;m Rifki.<br /><em>Most people call me Kinas.</em></h2><p>I&apos;m a software developer and the founder of NasLabs. I graduated from Institut Teknologi Kalimantan with a Bachelor&apos;s degree in Computer Science (S.Kom.).</p><p>My work sits around web applications, business websites, backend systems, and the practical engineering decisions that help software stay useful after it ships.</p><div className="profile-facts"><span><strong>Education</strong>Institut Teknologi Kalimantan<br />Sarjana Komputer (S.Kom.)</span><span><strong>Focus</strong>Web engineering<br />Digital products</span><span><strong>Based in</strong><MapPin aria-hidden="true" />Indonesia</span></div></div></section><section className="personal-note"><p className="eyebrow">A personal note</p><blockquote>&quot;I started NasLabs to create a space where I can stay close to the problem, make thoughtful engineering decisions, and build software that has a clear reason to exist.&quot;</blockquote><p className="signature">— Rifki Anashirul / Kinas</p></section><section className="principles"><p className="eyebrow">Working principles</p><div className="principle-grid"><div><strong>01</strong><h2>Clarity before complexity</h2><p>Understand the need before choosing the solution.</p></div><div><strong>02</strong><h2>Reliable over impressive</h2><p>Build things that are maintainable after launch.</p></div><div><strong>03</strong><h2>Progress in the open</h2><p>Keep scope, decisions, and trade-offs visible.</p></div></div></section><section className="page-cta"><div><p className="eyebrow">Work together</p><h2>Have a useful<br /><em>problem?</em></h2></div><Link className="text-link" href="/contact">Start a conversation <ArrowUpRight aria-hidden="true" /></Link></section></main>;
}
